-- =============================================================================
-- SUSTAINSULSE - ADMIN PRODUCTION READINESS
-- Apply after the historical root migrations. This migration is intentionally
-- idempotent and becomes the canonical schema/security baseline for the admin UI.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Trusted authorization helpers. Privileged roles come only from app_metadata.
CREATE OR REPLACE FUNCTION public.current_app_role()
RETURNS text
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT UPPER(COALESCE(auth.jwt() -> 'app_metadata' ->> 'role', 'STUDENT'));
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT public.current_app_role() IN ('ADMIN', 'SUPERADMIN', 'SUPER_ADMIN');
$$;

CREATE OR REPLACE FUNCTION public.is_instructor()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT public.current_app_role() IN ('INSTRUCTOR', 'TRAINER', 'TEACHER');
$$;

-- -----------------------------------------------------------------------------
-- 1. Close the live profiles disclosure and prevent profile privilege changes.
-- Unknown historical policies are removed so an old public SELECT policy cannot
-- survive this migration under another name.
-- -----------------------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles FORCE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.profiles FROM anon;
GRANT SELECT, UPDATE ON TABLE public.profiles TO authenticated;

DO $$
DECLARE policy_row record;
BEGIN
  FOR policy_row IN
    SELECT policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'profiles'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.profiles', policy_row.policyname);
  END LOOP;
END $$;

CREATE POLICY profiles_select_own_or_admin
  ON public.profiles FOR SELECT TO authenticated
  USING (id = auth.uid() OR public.is_admin());

CREATE POLICY profiles_update_own_or_admin
  ON public.profiles FOR UPDATE TO authenticated
  USING (id = auth.uid() OR public.is_admin())
  WITH CHECK (id = auth.uid() OR public.is_admin());

CREATE OR REPLACE FUNCTION public.protect_profile_security_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.role() <> 'service_role' AND NOT public.is_admin() THEN
    NEW.id := OLD.id;
    NEW.email := OLD.email;
    NEW.role := OLD.role;
    NEW.status := OLD.status;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS protect_profile_security_fields_trigger ON public.profiles;
CREATE TRIGGER protect_profile_security_fields_trigger
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.protect_profile_security_fields();

-- -----------------------------------------------------------------------------
-- 2. Normalize historically conflicting course_id/title quiz columns.
-- -----------------------------------------------------------------------------
DO $$
DECLARE course_id_type text;
BEGIN
  IF to_regclass('public.quizzes') IS NOT NULL THEN
    SELECT data_type INTO course_id_type
      FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'quizzes' AND column_name = 'course_id';
    IF course_id_type IS NOT NULL AND course_id_type <> 'text' THEN
      ALTER TABLE public.quizzes ALTER COLUMN course_id TYPE text USING course_id::text;
    END IF;
    ALTER TABLE public.quizzes ADD COLUMN IF NOT EXISTS title text;
    ALTER TABLE public.quizzes ADD COLUMN IF NOT EXISTS questions_json jsonb NOT NULL DEFAULT '[]'::jsonb;
    ALTER TABLE public.quizzes ADD COLUMN IF NOT EXISTS duration_minutes integer NOT NULL DEFAULT 30;
    ALTER TABLE public.quizzes ADD COLUMN IF NOT EXISTS pass_percentage integer NOT NULL DEFAULT 70;
    ALTER TABLE public.quizzes ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = 'quizzes' AND column_name = 'title_ar'
    ) THEN
      UPDATE public.quizzes SET title = title_ar WHERE title IS NULL;
    END IF;
  END IF;
END $$;

-- -----------------------------------------------------------------------------
-- 3. Relational, transactional storage for the catalog and certificates.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.course_catalog (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  price numeric(12,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS course_catalog_status_idx ON public.course_catalog(status);
CREATE INDEX IF NOT EXISTS course_catalog_payload_idx ON public.course_catalog USING gin(payload);

CREATE TABLE IF NOT EXISTS public.certificate_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  course_title text NOT NULL DEFAULT 'كافة الدورات التدريبية',
  image_url text,
  auto_issue boolean NOT NULL DEFAULT false,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS template_id uuid REFERENCES public.certificate_templates(id) ON DELETE SET NULL;
ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'active';
ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS payload jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.certificates ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS certificates_student_course_unique
  ON public.certificates (LOWER(email), course_id)
  WHERE email IS NOT NULL AND status = 'active';

-- -----------------------------------------------------------------------------
-- 4. Persistent editorial/service content (replaces client-only demo state).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_content_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind text NOT NULL CHECK (kind IN ('article', 'service')),
  slug text NOT NULL,
  title text NOT NULL,
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'active', 'inactive', 'archived')),
  is_featured boolean NOT NULL DEFAULT false,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(kind, slug)
);

CREATE INDEX IF NOT EXISTS admin_content_kind_status_idx ON public.admin_content_items(kind, status);

-- -----------------------------------------------------------------------------
-- 5. Immutable-ish admin audit log and notifications.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_audit_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  actor_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_email text,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text,
  request_id uuid NOT NULL DEFAULT gen_random_uuid(),
  ip_hash text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS admin_audit_created_idx ON public.admin_audit_log(created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_resource_idx ON public.admin_audit_log(resource_type, resource_id);

CREATE TABLE IF NOT EXISTS public.admin_notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  message text NOT NULL,
  href text,
  severity text NOT NULL DEFAULT 'info' CHECK (severity IN ('info', 'success', 'warning', 'error')),
  audience_role text NOT NULL DEFAULT 'ADMIN',
  read_by uuid[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 6. Paid access is granted by verified integrations, never by the browser.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.course_entitlements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  email text NOT NULL,
  course_id text NOT NULL,
  source text NOT NULL CHECK (source IN ('ghl_webhook', 'order', 'admin_grant')),
  source_reference text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked', 'expired')),
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS course_entitlements_active_unique
  ON public.course_entitlements(LOWER(email), course_id)
  WHERE status = 'active';

-- -----------------------------------------------------------------------------
-- 7. RLS baseline for all new admin-owned data.
-- -----------------------------------------------------------------------------
ALTER TABLE public.course_catalog ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certificate_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_content_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_entitlements ENABLE ROW LEVEL SECURITY;

CREATE POLICY course_catalog_public_read ON public.course_catalog FOR SELECT
  USING (status = 'published' OR public.is_admin() OR public.is_instructor());
CREATE POLICY course_catalog_staff_manage ON public.course_catalog FOR ALL TO authenticated
  USING (public.is_admin() OR public.is_instructor())
  WITH CHECK (public.is_admin() OR public.is_instructor());

CREATE POLICY certificate_templates_authenticated_read ON public.certificate_templates FOR SELECT TO authenticated
  USING (true);
CREATE POLICY certificate_templates_admin_manage ON public.certificate_templates FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY admin_content_public_read ON public.admin_content_items FOR SELECT
  USING (
    (kind = 'article' AND status = 'published')
    OR (kind = 'service' AND status = 'active')
    OR public.is_admin()
  );
CREATE POLICY admin_content_admin_manage ON public.admin_content_items FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY admin_audit_admin_read ON public.admin_audit_log FOR SELECT TO authenticated
  USING (public.is_admin());

CREATE POLICY admin_notifications_admin_access ON public.admin_notifications FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

CREATE POLICY entitlements_own_or_admin_read ON public.course_entitlements FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR LOWER(email) = LOWER(auth.jwt() ->> 'email') OR public.is_admin());
CREATE POLICY entitlements_admin_manage ON public.course_entitlements FOR ALL TO authenticated
  USING (public.is_admin()) WITH CHECK (public.is_admin());

-- The service role remains the only writer used by server-side DALs/audit hooks.
REVOKE INSERT, UPDATE, DELETE ON public.admin_audit_log FROM anon, authenticated;
REVOKE ALL ON public.course_entitlements FROM anon;
REVOKE ALL ON public.certificate_templates FROM anon;
GRANT SELECT ON public.course_catalog, public.admin_content_items TO anon, authenticated;
GRANT SELECT ON public.certificate_templates, public.admin_notifications, public.course_entitlements TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.course_catalog, public.admin_content_items TO authenticated;

-- Storage objects are not used as a database. Buckets below hold only media.
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('course-thumbnails', 'course-thumbnails', true, 5242880, ARRAY['image/jpeg','image/png','image/webp']),
  ('certificate-templates', 'certificate-templates', true, 10485760, ARRAY['image/jpeg','image/png','image/webp']),
  ('student-submissions', 'student-submissions', false, 52428800, NULL)
ON CONFLICT (id) DO UPDATE SET
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- Explicitly remove the obsolete JSON database object if a deployment chooses
-- to do so after running the data migration script. No SQL deletion is performed.

COMMENT ON TABLE public.admin_audit_log IS 'Append-only audit events written by service-role server routes.';
COMMENT ON TABLE public.course_catalog IS 'Canonical relational course catalog. payload contains the typed Course DTO.';
